/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Karyawan;
import util.DbQuery;

/**
 *
 * @author didan
 */
public class CreateKaryawan extends javax.swing.JFrame {

    /** Creates new form CreateKaryawan */
    public CreateKaryawan() {
        initComponents();
        String[] jabatan = {"Manager", "Kepala Bidang", "Staff", "Pegawai"};
        inputJabatan.removeAllItems();
        for(String j : jabatan) {
            inputJabatan.addItem(j);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputJabatan = new javax.swing.JComboBox<>();
        inputAnak = new javax.swing.JTextField();
        inputJam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TAMBAH DATA KARYAWAN");

        inputName.setText("Nama");
        inputName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNameFocusGained(evt);
            }
        });
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        inputJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inputAnak.setText("Jumlah anak");
        inputAnak.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputAnakFocusGained(evt);
            }
        });
        inputAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAnakActionPerformed(evt);
            }
        });

        inputJam.setText("Total Jam Kerja");
        inputJam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputJamFocusGained(evt);
            }
        });
        inputJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJamActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputJam, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputJam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAnakActionPerformed

    private void inputJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJamActionPerformed

    private void inputNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNameFocusGained
        inputName.setText("");
    }//GEN-LAST:event_inputNameFocusGained

    private void inputJamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputJamFocusGained
        inputJam.setText("");
    }//GEN-LAST:event_inputJamFocusGained

    private void inputAnakFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAnakFocusGained
        inputAnak.setText("");
    }//GEN-LAST:event_inputAnakFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //add process
        long[][] gaji = {
            {65000, 800000, 1300000, 2200000, 4000000},
            {60000, 500000, 800000, 1400000, 3000000},
            {50000, 500000, 800000, 1400000, 2000000},
            {30000, 300000, 500000, 900000, 1500000}
        };
        int jamLembur = 0; 
        long tunjAnak = 0, tunjLembur, total = 0;
        int jamKerja = Integer.parseInt(inputJam.getText());
        int jabatan = inputJabatan.getSelectedIndex();
        int anak = Integer.parseInt(inputAnak.getText());
        
        if(jamKerja > 160) jamLembur = jamKerja - 160;
        tunjLembur = jamLembur * gaji[jabatan][0];
        
        if(anak > 4) tunjAnak = gaji[jabatan][3];
        else if(anak >= 2) tunjAnak = gaji[jabatan][2];
        else if(anak == 1) tunjAnak = gaji[jabatan][1];
        
        total += gaji[jabatan][4];
        total += tunjAnak;
        total += tunjLembur;
        total += gaji[jabatan][4] * 0.05;
        
        Karyawan karyawan = new Karyawan();
        karyawan.setNama(inputName.getText());
        karyawan.setJabatan(jabatan+1);
        karyawan.setGaji(total);
        
        try {
            DbQuery.insertKaryawan(karyawan);
            this.setVisible(false);
            new ListKaryawan().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CreateKaryawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateKaryawan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputAnak;
    private javax.swing.JComboBox<String> inputJabatan;
    private javax.swing.JTextField inputJam;
    private javax.swing.JTextField inputName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
